quarkus.kafka.devservices.enabled=true
mp.messaging.incoming.orders.connector=smallrye-kafka
mp.messaging.incoming.orders.topic=orders
mp.messaging.incoming.orders.commit-strategy=ignore
mp.messaging.incoming.orders.failure-strategy=ignore
mp.messaging.incoming.orders.auto.offset.reset=latest
mp.messaging.incoming.orders.enable.auto.commit=true
mp.messaging.incoming.orders.tracing-enabled=false
mp.messaging.incoming.orders.security.protocol=PLAINTEXT
mp.messaging.outgoing.notifications.connector=smallrye-kafka
mp.messaging.outgoing.notifications.topic=notifications
mp.messaging.outgoing.notifications.ssl.endpoint.identification.algorithm=
mp.messaging.outgoing.notifications.retries=0
mp.messaging.outgoing.notifications.acks=1
mp.messaging.outgoing.notifications.waitForWriteCompletion=false
mp.messaging.incoming.orders.health-enabled=false
mp.messaging.incoming.orders.graceful-shutdown=false
mp.messaging.incoming.audit.connector=smallrye-kafka
mp.messaging.incoming.audit.topic=audit
mp.messaging.incoming.audit.auto.offset.reset=none
mp.messaging.incoming.orders.fail-on-deserialization-failure=false
mp.messaging.incoming.tenants.connector=smallrye-kafka
mp.messaging.incoming.tenants.topic=tenant-.*-orders
mp.messaging.incoming.tenants.pattern=true
mp.messaging.incoming.broadcasts.connector=smallrye-kafka
mp.messaging.incoming.broadcasts.topic=broadcasts
mp.messaging.incoming.broadcasts.broadcast=true
mp.messaging.outgoing.shortClose.connector=smallrye-kafka
mp.messaging.outgoing.shortClose.topic=short-close
mp.messaging.outgoing.shortClose.close-timeout=1000
mp.messaging.incoming.shortThrottle.connector=smallrye-kafka
mp.messaging.incoming.shortThrottle.topic=short-throttle
mp.messaging.incoming.shortThrottle.throttled.unprocessed-record-max-age.ms=2000
mp.messaging.outgoing.pinned.connector=smallrye-kafka
mp.messaging.outgoing.pinned.topic=pinned-output
mp.messaging.outgoing.pinned.partition=0
mp.messaging.outgoing.firehose.connector=smallrye-kafka
mp.messaging.outgoing.firehose.topic=firehose
mp.messaging.outgoing.firehose.max-inflight-messages=100000
mp.messaging.outgoing.firehose.ssl.enabled.protocols=TLSv1.2,TLSv1.1
mp.messaging.outgoing.firehose.ssl.cipher.suites=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_RC4_128_SHA
kafka.bootstrap.servers=localhost:9092
