quarkus.kafka.devservices.enabled=true
mp.messaging.incoming.orders.connector=smallrye-kafka
mp.messaging.incoming.orders.topic=orders
mp.messaging.incoming.orders.commit-strategy=ignore
mp.messaging.incoming.orders.failure-strategy=ignore
mp.messaging.incoming.orders.auto.offset.reset=latest
mp.messaging.incoming.orders.enable.auto.commit=true
mp.messaging.incoming.orders.tracing-enabled=false
mp.messaging.incoming.orders.security.protocol=PLAINTEXT
mp.messaging.outgoing.notifications.connector=smallrye-kafka
mp.messaging.outgoing.notifications.topic=notifications
mp.messaging.outgoing.notifications.ssl.endpoint.identification.algorithm=
