spring.kafka.producer.batch-size=2MB
spring.kafka.producer.properties.delivery.timeout.ms=900000
spring.kafka.producer.properties.max.request.size=20971520
spring.kafka.producer.properties.request.timeout.ms=180000
spring.kafka.producer.compression-type=gzip
