spring.kafka.consumer.auto-commit-interval=50
spring.kafka.consumer.session-timeout=5s
spring.kafka.consumer.heartbeat-interval=200ms
spring.kafka.producer.properties.transaction.timeout.ms=3600000
spring.kafka.consumer.auto-offset-reset=none
spring.kafka.listener.concurrency=128
spring.kafka.streams.properties.task.timeout.ms=3600000
spring.kafka.streams.properties.num.stream.threads=128
spring.kafka.streams.properties.repartition.purge.interval.ms=1000
spring.kafka.streams.replication-factor=-1
spring.kafka.streams.properties.buffered.records.per.partition=50
spring.kafka.producer.acks=yes
spring.kafka.consumer.properties.max.partition.fetch.bytes=512
