spring.kafka.consumer.max-poll-records=10000
spring.kafka.producer.properties.linger.ms=10000
spring.kafka.producer.properties.delivery.timeout.ms=15000
spring.kafka.producer.buffer-memory=536870912
spring.kafka.consumer.fetch-min-size=50MB
spring.kafka.consumer.fetch-max-wait=30s
spring.kafka.consumer.properties.max.poll.interval.ms=3600000
spring.kafka.consumer.fetch-max-size=512KB
spring.kafka.streams.properties.processing.guarantee=at_least_once
spring.kafka.streams.replication-factor=7
spring.kafka.consumer.auto-offset-reset=oldest
spring.kafka.producer.properties.max.block.ms=600000
spring.kafka.bootstrap-servers=${BOOTSTRAP}:9092
spring.kafka.streams.application-id=${STREAMS_APP}
spring.kafka.streams.properties.application.server=${IQ_HOST}:${IQ_PORT}
