spring.kafka.producer.batch-size=2MB
spring.kafka.producer.properties.delivery.timeout.ms=900000
spring.kafka.producer.properties.max.request.size=20971520
spring.kafka.producer.properties.request.timeout.ms=180000
spring.kafka.producer.compression-type=gzip
spring.kafka.consumer.fetch-max-size=500MB
spring.kafka.producer.properties.partitioner.class=org.apache.kafka.clients.producer.UniformStickyPartitioner
spring.kafka.streams.replication-factor=2
spring.kafka.streams.properties.commit.interval.ms=300000
spring.kafka.streams.properties.default.timestamp.extractor=org.apache.kafka.streams.processor.WallclockTimestampExtractor
spring.kafka.streams.properties.num.standby.replicas=5
spring.kafka.streams.properties.probing.rebalance.interval.ms=14400000
spring.kafka.consumer.properties.default.api.timeout.ms=900000
spring.kafka.consumer.fetch-max-size=200MB
spring.kafka.producer.properties.reconnect.backoff.ms=10
spring.kafka.producer.properties.retry.backoff.ms=20
spring.kafka.producer.client-id=producer
