spring.kafka.consumer.max-poll-records=10000
spring.kafka.producer.properties.linger.ms=10000
spring.kafka.producer.properties.delivery.timeout.ms=15000
spring.kafka.producer.buffer-memory=536870912
spring.kafka.consumer.fetch-min-size=50MB
spring.kafka.consumer.fetch-max-wait=30s
spring.kafka.consumer.properties.max.poll.interval.ms=3600000
