spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.acks=1
spring.kafka.consumer.enable-auto-commit=true
spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.properties.security.protocol=SASL_PLAINTEXT
spring.kafka.properties.ssl.endpoint.identification.algorithm=
spring.kafka.properties.auto.register.schemas=true
spring.kafka.properties.use.latest.version=true
spring.kafka.properties.schema.registry.url=http://schema-registry:8081
spring.kafka.producer.compression-type=none
spring.kafka.producer.retries=0
spring.kafka.listener.concurrency=0
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="svc" password="hunter2";
spring.kafka.properties.basic.auth.user.info=sr-user:sr-secret
spring.kafka.ssl.key-store-password=changeit
spring.kafka.consumer.auto-commit-interval=300000
spring.kafka.producer.transaction-id-prefix=tx-
spring.kafka.template.observation-enabled=false
spring.kafka.listener.observation-enabled=false
spring.kafka.producer.batch-size=1024
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.producer.properties.linger.ms=0
spring.kafka.consumer.group-id=app
spring.kafka.consumer.max-poll-records=1
spring.kafka.listener.ack-mode=RECORD
